# serverless.yml


service: xc-serverless-example-rest

provider:
  name: aws
  runtime: nodejs12.x
  stage: production
  region: us-east-1
  websocketsApiName: xc-serverless-websockets-api
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body


functions:
  app:
    handler: server/app.serverless
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
    environment:
      NODE_ENV: 'production'
